Fix for the freeze issue and CTRL+L
transferdev/Transfercoin pull request #55
Opened 2017-05-02 18:00 UTC by syfares

2017-05-02 18:42 UTC, Infernoman requested changes

2017-05-02 18:42 UTC, Infernoman commented on src/masternodeconfig.cpp
> -        if(Params().NetworkID() == CChainParams::MAIN){
this is the part I was speaking about, which checks the port. one more to check that it is on an IPV4 ;)

2017-05-02 18:42 UTC, Infernoman commented on src/masternodeconfig.cpp
> -            return false;
and lines 41-50 through here, which checks that the IP in the masternode.conf file is IPV4 and is routable.

2017-05-02 21:53 UTC, syfares commented
Right will provide the update i

2017-05-03 06:44 UTC, Infernoman commented
Close ;) the daemon builds successfully on linux with travis but the QT does not.

2017-05-03 22:41 UTC, syfares commented
Thanks, tried a new version based on my current directory for compilation
Lots of change especially on secp256k1

2017-05-04 06:04 UTC, syfares commented
Still no good, I think commiting from my MAC did not help, will have to stick with the windows build to keep all library correct

2017-05-04 18:11 UTC, syfares commented
Looks better :)

2017-05-04 18:55 UTC, Infernoman approved these changes

2017-05-04 18:56 UTC, Infernoman commented
great news :) im going to get in touch with the guys on the team and see if there is anything else they would like to do before an official release. I'll get this merged in now.

2017-05-04 18:57 UTC, merged